export enum StatusLoan {
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  DELIVERED = 'DELIVERED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  RETURNED_LATE = 'RETURNED_LATE',
}
