import {
  normativeType,
  origin,
  certificateType,
  certificateStatus,
  policyStatus,
  maintenanceType,
  maintenanceStatus,
  assetLoanStatus,
  exitProcessType,
  exitProcessStatus,
  claimStatus,
  labelType,
  labelFormat,
  labelStatus,
  loanStatus,
  documentType,
  locationType,
  movementType,
  capacityUnit,
  notificationType,
  notificationStatus,
  notificationChannel,
  deliveryStatus,
  verificationStatus,
  foundStatus,
  reportType,
  reportFormat,
  reportFrequency,
  userType,
  userStatus,
} from './schema/enums'
import {
  item,
  itemRelations,
  itemType,
  itemTypeRelations,
  category,
  categoryRelations,
  status,
  statusRelations,
  condition,
  conditionRelations,
  certificate,
  certificateRelations,
  color,
  colorRelations,
  material,
  materialRelations,
  itemColor,
  itemColorRelations,
  itemMaterial,
  itemMaterialRelations,
  itemImage,
  itemImageRelations,
  assetValue,
  assetValueRelations,
  depreciation,
  depreciationRelations,
  maintenance,
  movement,
  statusChange,
  insurancePolicy,
  insurancePolicyRelations,
  insuredAssetDetail,
  insuredAssetDetailRelations,
  insuranceClaim,
  insuranceClaimRelations,
  exitProcess,
  exitProcessRelations,
  exitDetail,
  exitDetailRelations,
  assetLoan,
} from './schema/tables/inventory'
import {
  label,
  labelRelations,
  labelTemplate,
  scanRecord,
  scanRecordRelations,
} from './schema/tables/labeling'
import {
  loan,
  loanRelations,
  loanDetail,
  loanDetailRelations,
  loanHistory,
  responsibilityDocument,
} from './schema/tables/loans'
import {
  warehouse,
  warehouseRelations,
  locationRelations,
  location,
} from './schema/tables/locations'
import {
  notification,
  notificationRelations,
  notificationPreference,
  notificationPreferenceRelations,
  notificationTemplate,
  deliveryRecord,
  deliveryRecordRelations,
} from './schema/tables/notifications'
import {
  physicalVerification,
  physicalVerificationRelations,
  verificationDetail,
  verificationDetailRelations,
  generatedReport,
  generatedReportRelations,
  reportTemplate,
  inventoryStatistics,
} from './schema/tables/reports'
import {
  user,
  role,
  roleRelations,
  person,
  userRole,
  userRoleRelations,
} from './schema/tables/users'

export {
  person,
  user,
  role,
  roleRelations,
  userRole,
  userRoleRelations,

  // Ubicaciones
  warehouse,
  warehouseRelations,
  location,
  locationRelations,

  // Inventario - tablas principales
  item,
  itemRelations,
  itemType as assetType,
  itemTypeRelations as assetTypeRelations,
  category,
  categoryRelations,
  status,
  statusRelations,
  condition,
  conditionRelations,
  certificate,
  certificateRelations,

  // Características, colores y materiales
  color,
  colorRelations,
  material,
  materialRelations,
  itemColor,
  itemColorRelations,
  itemMaterial,
  itemMaterialRelations,
  itemImage,
  itemImageRelations,

  // Valor y depreciación
  assetValue,
  assetValueRelations,
  depreciation,
  depreciationRelations,

  // Mantenimiento y movimientos
  maintenance,
  movement,
  statusChange,

  // Seguros
  insurancePolicy,
  insurancePolicyRelations,
  insuredAssetDetail,
  insuredAssetDetailRelations,
  insuranceClaim,
  insuranceClaimRelations,

  // Salida de activos
  exitProcess,
  exitProcessRelations,
  exitDetail,
  exitDetailRelations,
  assetLoan,

  // Préstamos
  loan,
  loanRelations,
  loanDetail,
  loanDetailRelations,
  loanHistory,
  responsibilityDocument,

  // Etiquetas
  label,
  labelRelations,
  labelTemplate,
  scanRecord,
  scanRecordRelations,

  // Reportes
  physicalVerification,
  physicalVerificationRelations,
  verificationDetail,
  verificationDetailRelations,
  generatedReport,
  generatedReportRelations,
  reportTemplate,
  inventoryStatistics,

  // Notificaciones
  notification,
  notificationRelations,
  notificationPreference,
  notificationPreferenceRelations,
  notificationTemplate,
  deliveryRecord,
  deliveryRecordRelations,

  //enums
  normativeType,
  origin,
  certificateType,
  certificateStatus,
  policyStatus,
  maintenanceType,
  maintenanceStatus,
  assetLoanStatus,
  exitProcessType,
  exitProcessStatus,
  claimStatus,
  labelType,
  labelFormat,
  labelStatus,
  loanStatus,
  documentType,
  locationType,
  movementType,
  capacityUnit,
  notificationType,
  notificationStatus,
  notificationChannel,
  deliveryStatus,
  verificationStatus,
  foundStatus,
  reportType,
  reportFormat,
  reportFrequency,
  userType,
  userStatus,
}
